apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shared-infra.labels" . | nindent 4 }}
spec:
  replicas: {{ if eq .Values.global.environment "production" }}3{{ else }}1{{ end }}
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        {{- include "shared-infra.labels" . | nindent 8 }}
        app: vault
    spec:
      securityContext:
        fsGroup: 100
        fsGroupChangePolicy: "OnRootMismatch"
      serviceAccountName: vault
      containers:
        - name: vault
          image: vault:1.13.3
          command: ["vault", "server", "-config=/vault/config/vault.hcl"]
          env:
            - name: SKIP_SETCAP
              value: "true"
            - name: VAULT_SKIP_VERIFY
              value: "true"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          securityContext:
            capabilities:
              add: 
                - IPC_LOCK
                - SETFCAP
            runAsUser: 100
            runAsNonRoot: true
            allowPrivilegeEscalation: true
          ports:
            - containerPort: 8200
              name: http
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          volumeMounts:
            - name: config
              mountPath: /vault/config
            - name: data
              mountPath: /vault/data
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: vault-config
            defaultMode: 0644
            items:
              - key: vault.hcl
                path: vault.hcl
                mode: 0644
        - name: data
          {{- if and .Values.vault.persistence (eq .Values.vault.persistence.enabled true) }}
          persistentVolumeClaim:
            claimName: vault-data
          {{- else }}
          emptyDir: {}
          {{- end }}
      nodeSelector:
        kubernetes.io/hostname: template-validator-control-plane
