apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv-{{ .Release.Namespace }}
  labels:
    {{- include "shared-infra.labels" . | nindent 4 }}
    type: local
    pv-name: vault-pv-{{ .Release.Namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vault-storage-{{ .Release.Namespace }}
  hostPath:
    path: /data/vault/{{ .Release.Namespace }}
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - template-validator-control-plane
