apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shared-infra.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vault-storage-{{ .Release.Namespace }}
  selector:
    matchLabels:
      pv-name: vault-pv-{{ .Release.Namespace }}
  resources:
    requests:
      storage: 1Gi