apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shared-infra.labels" . | nindent 4 }}
spec:
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200
      name: http
