apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vault-storage-{{ .Release.Namespace }}
  labels:
    {{- include "shared-infra.labels" . | nindent 4 }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/local-storage
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
