name: Release Chart

on:
  push:
    branches:
      - master
    paths:
      - "Chart.yaml"
      - "values.yaml"
      - "templates/**"
      - ".github/workflows/release.yaml"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.20.0"

      - name: Install Gateway API CRDs
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm chart
        run: helm package ./charts

      - name: Push Chart
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          helm push *.tgz oci://ghcr.io/${GITHUB_REPOSITORY,,}/charts

      - name: Update Version
        if: success()
        run: |
          echo "Successfully published chart version $(helm show chart . | grep version | cut -d' ' -f2)"
